// Package iconlabel consolidates noisy VLM icon labels into a confident concept
// via a Lucide-derived alias map (TF-IDF weak-flagged) plus majority voting.
//
// The technique was selected by measurement (see docs/roadmap): Lucide tags +
// TF-IDF weak-flagging + N-run voting + over-long-run filter scored best
// (7.0/10 self-consistency, 4/5 correct) against vectorization, WordNet, a
// react-icons vocabulary, a hand map, and tag co-occurrence.
//
// The embedded alias map is derived from Lucide's per-icon tag metadata
// (ISC-licensed; see THIRD_PARTY_LICENSES) and generated by dev/genlucidemap.
package iconlabel

import (
	_ "embed"
	"encoding/json"
	"regexp"
	"strings"
)

//go:embed data/lucide_aliases.json
var aliasJSON []byte

// aliasEntry mirrors the generated JSON map value.
type aliasEntry struct {
	Concept string  `json:"concept"`
	Weak    bool    `json:"weak"`
	IDF     float64 `json:"idf"`
}

// maxLabelWordsDefault rejects rambling model outputs before voting: a real
// icon name is a few words; long outputs are refusals/descriptions that would
// inject spurious tokens. Overridable per model via NewWithProfile.
const maxLabelWordsDefault = 4

var wordRe = regexp.MustCompile(`[a-z]+`)

var stopwords = map[string]bool{
	"icon": true, "button": true, "a": true, "an": true, "the": true,
	"of": true, "with": true, "gray": true, "grey": true, "image": true,
	"symbol": true, "glyph": true, "small": true, "dark": true, "on": true,
	"in": true, "it": true, "is": true, "this": true, "that": true,
	"appears": true, "to": true, "be": true, "represents": true, "and": true,
	"or": true, "for": true,
}

// defaultGarbageMarkers flag format-garbage (code/markup) small VLMs emit.
var defaultGarbageMarkers = []string{"<svg", "```", "viewbox", "{", "http", "path fill"}

// Canonicalizer maps free-text icon labels to canonical concept keys, using a
// per-model output profile for the noise filters (max label words, garbage
// markers).
type Canonicalizer struct {
	alias          map[string]aliasEntry
	maxLabelWords  int
	garbageMarkers []string
}

// New builds a Canonicalizer with default (model-agnostic) noise filters.
func New() (*Canonicalizer, error) {
	return NewWithProfile(maxLabelWordsDefault, defaultGarbageMarkers)
}

// NewWithProfile builds a Canonicalizer with model-specific noise filters.
// A maxLabelWords <= 0 or nil markers fall back to the defaults.
func NewWithProfile(maxLabelWords int, garbageMarkers []string) (*Canonicalizer, error) {
	var m map[string]aliasEntry
	if err := json.Unmarshal(aliasJSON, &m); err != nil {
		return nil, err
	}
	if maxLabelWords <= 0 {
		maxLabelWords = maxLabelWordsDefault
	}
	if len(garbageMarkers) == 0 {
		garbageMarkers = defaultGarbageMarkers
	}
	return &Canonicalizer{alias: m, maxLabelWords: maxLabelWords, garbageMarkers: garbageMarkers}, nil
}

// Canonicalize reduces a raw VLM label to a canonical concept key, or "" if the
// label is garbage, too long, or unresolvable. Weak (common/ambiguous) aliases
// are only used as a last resort, so distinctive/multi-word matches win.
func (c *Canonicalizer) Canonicalize(text string) string {
	low := strings.ToLower(text)
	for _, g := range c.garbageMarkers {
		if strings.Contains(low, g) {
			return ""
		}
	}
	var words []string
	for _, w := range wordRe.FindAllString(low, -1) {
		if !stopwords[w] {
			words = append(words, w)
		}
	}
	if len(words) == 0 || len(words) > c.maxLabelWords {
		return ""
	}

	// 1. Whole phrase, strong (non-weak) match.
	if e, ok := c.alias[strings.Join(words, " ")]; ok && !e.Weak {
		return e.Concept
	}
	// 2. Bigrams, strong.
	for i := 0; i+1 < len(words); i++ {
		if e, ok := c.alias[words[i]+" "+words[i+1]]; ok && !e.Weak {
			return e.Concept
		}
	}
	// 3. Single tokens, strong.
	for _, w := range words {
		if e, ok := c.alias[w]; ok && !e.Weak {
			return e.Concept
		}
	}
	// 4. Last resort: any resolution, including weak.
	if e, ok := c.alias[strings.Join(words, " ")]; ok {
		return e.Concept
	}
	for _, w := range words {
		if e, ok := c.alias[w]; ok {
			return e.Concept
		}
	}
	return ""
}

// VoteResult is the outcome of voting over repeated labels.
type VoteResult struct {
	Concept   string  // the winning canonical concept ("" if none)
	Agreement int     // how many samples resolved to Concept
	Samples   int     // total samples considered
	Ratio     float64 // Agreement/Samples (0 when Samples==0)
}

// Vote canonicalizes each raw label and returns the modal concept plus its
// agreement. Empty/garbage/over-long labels are ignored (do not count toward a
// concept but do count toward Samples).
func (c *Canonicalizer) Vote(rawLabels []string) VoteResult {
	tally := map[string]int{}
	for _, r := range rawLabels {
		if k := c.Canonicalize(r); k != "" {
			tally[k]++
		}
	}
	best, k := "", 0
	for concept, n := range tally {
		if n > k || (n == k && concept < best) {
			best, k = concept, n
		}
	}
	ratio := 0.0
	if len(rawLabels) > 0 {
		ratio = float64(k) / float64(len(rawLabels))
	}
	return VoteResult{Concept: best, Agreement: k, Samples: len(rawLabels), Ratio: ratio}
}
